import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@tecbunny/core/context/AppProvider";
import { EnterpriseAnalyticsAutoTracker } from "@tecbunny/core/components/EnterpriseAnalyticsAutoTracker";
import { TRPCProvider } from "../components/providers/TRPCProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{
        ['--font-geist-sans' as string]: 'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
        ['--font-geist-mono' as string]: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      }}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AppProvider>
          <TRPCProvider>
            <EnterpriseAnalyticsAutoTracker application="mgmt" defaultModule="management" dashboardPaths={['/mgmt', '/admin', '/analytics']} />
            {children}
          </TRPCProvider>
        </AppProvider>
      </body>
    </html>
  );
}
