'use client';
import Link from 'next/link';
import { ArrowRight, Building2, Camera, Monitor, Network, Search, ShieldCheck, Smartphone, Ticket, Wifi } from 'lucide-react';

const categories = [
  ['Computers & Mobiles', 'Buy, repair, upgrade or accessorise your devices.', '/services/computers-mobiles', Monitor],
  ['Networking & Internet', 'Wi-Fi, routers, installations and Jio AirFiber help.', '/services/networking-internet', Wifi],
  ['CCTV & Security', 'Cameras, installation, repairs and protection for your property.', '/services/cctv-security', Camera],
  ['Government & Business', 'Documents, registrations and practical business support.', '/services/government-business', Building2],
  ['Financial & Travel', 'Insurance, payments, money transfer and ticket bookings.', '/services/financial-travel', Ticket],
] as const;
const popular = [['CCTV Installation','/services/cctv-security'],['Computer & Laptop Repair','/services/computers-mobiles'],['Wi-Fi & Network Setup','/services/networking-internet'],['Jio AirFiber','/services/networking-internet'],['PAN Card Services','/services/government-business'],['GST Registration','/services/government-business'],['Insurance','/services/financial-travel'],['Train, Bus & Flight Tickets','/services/financial-travel']];

export default function HomePage(_props: { initialPartnerBrands?: Array<{ name: string; logoUrl: string }>; initialHeroCarousel?: unknown }) { return <div className="bg-zinc-950 text-white">
  <section className="border-b border-zinc-800 bg-[radial-gradient(circle_at_80%_0%,rgba(37,99,235,.24),transparent_34%),linear-gradient(180deg,#10182a_0%,#09090b_85%)]"><div className="tb-container py-14 sm:py-20 lg:py-24"><div className="max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-400/10 px-3 py-1.5 text-sm font-semibold text-blue-200"><ShieldCheck size={16}/> Local support in Goa</p><h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Technology, connectivity &amp; digital services — all in one place.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-zinc-300">From computer repairs and CCTV installation to Wi-Fi, government services, insurance and ticketing, TecBunny helps you get things done.</p><form action="/services" className="mt-8 flex max-w-2xl items-center gap-3 rounded-2xl border border-zinc-700 bg-zinc-900 p-2 shadow-2xl"><Search className="ml-2 shrink-0 text-zinc-400"/><input name="query" aria-label="Search TecBunny services" className="min-w-0 flex-1 bg-transparent px-1 py-3 text-base outline-none placeholder:text-zinc-500" placeholder="Search CCTV, laptop repair, GST, insurance..."/><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold hover:bg-blue-500">Search</button></form></div></div></section>
  <section className="tb-container py-12 sm:py-16"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-400">Start here</p><h2 className="mt-2 text-3xl font-bold">What do you need today?</h2></div><Link href="/services" className="hidden text-sm font-semibold text-blue-300 hover:text-white sm:block">View all services <ArrowRight className="inline" size={16}/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{categories.map(([title,copy,href,Icon]) => <Link key={title} href={href} className="group rounded-2xl border border-zinc-800 bg-zinc-900/70 p-5 transition hover:-translate-y-1 hover:border-blue-500/60 hover:bg-zinc-900"><Icon className="mb-7 text-blue-400" size={30}/><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-zinc-400">{copy}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-blue-300">Explore <ArrowRight size={15}/></span></Link>)}</div></section>
  <section className="border-y border-zinc-800 bg-zinc-900/40"><div className="tb-container py-12"><h2 className="text-2xl font-bold">Need help?</h2><p className="mt-2 text-zinc-400">Choose a common request and we’ll take you to the right place.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Repair my device','/services/computers-mobiles',Smartphone],['Install CCTV','/services/cctv-security',Camera],['Fix my Wi-Fi','/services/networking-internet',Network],['Buy a product','/products',Monitor],['Government service','/services/government-business',Building2],['Contact TecBunny','/contact',ShieldCheck]].map(([label,href,Icon]) => { const I=Icon as typeof Camera; return <Link key={label as string} href={href as string} className="flex min-h-14 items-center gap-3 rounded-xl border border-zinc-700 bg-zinc-950 px-4 font-semibold hover:border-blue-500 hover:text-blue-200"><I size={20} className="text-blue-400"/>{label as string}<ArrowRight size={16} className="ml-auto"/></Link>})}</div></div></section>
  <section className="tb-container py-12 sm:py-16"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-widest text-blue-400">Popular services</p><h2 className="mt-2 text-3xl font-bold">Get to the right service, faster.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{popular.map(([label,href]) => <Link key={label} href={href} className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-4 text-base font-semibold hover:border-blue-500 hover:text-blue-200">{label}<ArrowRight size={16} className="float-right mt-1 text-blue-400"/></Link>)}</div><Link href="/services" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-xl border border-blue-500 bg-blue-600 px-5 font-bold hover:bg-blue-500">View all services <ArrowRight size={17}/></Link></section>
  <section className="border-t border-zinc-800"><div className="tb-container grid gap-8 py-12 sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="text-2xl font-bold">Prefer to speak with someone?</h2><p className="mt-2 text-zinc-400">Tell us what you need and our local team will guide you.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="https://wa.me/919604136010" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-emerald-600 px-5 font-bold hover:bg-emerald-500">WhatsApp us</a><Link href="/contact" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-zinc-700 px-5 font-bold hover:border-blue-400">Request service</Link></div></div></section>
</div>; }
