'use client';

import * as React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowRight, ChevronDown, Globe, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { Logo } from '@tecbunny/ui';
import { logger, useAnalytics } from '@tecbunny/core';
import { ENTITY } from '@/lib/entity';

const DEFAULT_COMPANY_INFO = { supportEmail: 'support@tecbunny.com', supportPhone: '+91 96041 36010', registeredAddress: 'H. No. 11, Nhayginwada, Parse, Parxem, Pernem, North Goa, Goa - 403512', gstin: '30AAMCT1608G1ZO' };
const FALLBACK_SOCIAL_LINKS = { facebookUrl: 'https://www.facebook.com/profile.php?id=61578165368064', instagramUrl: 'https://www.instagram.com/tecbunny_solutions/', twitterUrl: process.env.NEXT_PUBLIC_X_URL || '' };
type FooterLink = { label: string; href: string };

const linkGroups: { title: string; links: FooterLink[] }[] = [
  { title: 'Solutions', links: [{ label: 'Network & IT Infrastructure', href: '/services/network-infrastructure' }, { label: 'CCTV & Security', href: '/services/physical-security' }, { label: 'Access Control', href: '/services/smart-access-control' }, { label: 'IT Support & AMC', href: '/services/lifecycle-hardware' }, { label: 'Custom Setups', href: '/customised-setups' }] },
  { title: 'Products', links: [{ label: 'Browse all products', href: '/products' }, { label: 'Computers & laptops', href: '/products' }, { label: 'CCTV & security equipment', href: '/products' }, { label: 'Networking equipment', href: '/products' }, { label: 'Accessories & storage', href: '/products' }] },
  { title: 'Industries', links: [{ label: 'Hotels & resorts', href: '/industries/hospitality' }, { label: 'Offices & co-working', href: '/industries/offices' }, { label: 'Retail & commercial', href: '/industries/retail' }, { label: 'Education & campuses', href: '/industries/education' }, { label: 'Healthcare', href: '/industries/healthcare' }] },
  { title: 'Help', links: [{ label: 'Get help choosing', href: '/contact?intent=help_me_choose&source=footer' }, { label: 'Request a quote', href: '/contact?intent=quote_request&source=footer' }, { label: 'Book a site survey', href: '/assessment' }, { label: 'Repair & support', href: '/contact?intent=service_request&source=footer' }, { label: 'FAQs', href: '/info/faqs' }] },
  { title: 'Company', links: [{ label: 'About TecBunny', href: '/about' }, { label: 'Projects', href: '/projects' }, { label: 'Industries', href: '/industries' }, { label: 'Contact', href: '/contact' }, { label: 'Careers', href: '/agents/recruit' }] },
];

function FacebookIcon(props: React.SVGProps<SVGSVGElement>) { return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><path d="M13.5 22v-8h2.7l.4-3.1h-3.1V8.9c0-.9.3-1.5 1.6-1.5h1.7V4.6c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3v2.4H7.3V14h2.8v8h3.4Z" /></svg>; }
function InstagramIcon(props: React.SVGProps<SVGSVGElement>) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true" {...props}><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none" /></svg>; }
function XIcon(props: React.SVGProps<SVGSVGElement>) { return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><path d="M18.9 3h3.2l-7 8 8.2 10h-6.4l-5-6.1L6.2 21H3l7.5-8.6L2.7 3h6.6l4.5 5.5L18.9 3Zm-1.1 16.2h1.8L8.3 4.7H6.4l11.4 14.5Z" /></svg>; }
function LinkedinIcon(props: React.SVGProps<SVGSVGElement>) { return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><path d="M6.9 21H3.5V9h3.4v12ZM5.2 7.4a2 2 0 1 1 0-4 2 2 0 0 1 0 4ZM21 21h-3.4v-5.9c0-1.4 0-3.1-1.9-3.1s-2.2 1.5-2.2 3v6H10V9h3.3v1.6h.1c.5-.9 1.6-1.9 3.3-1.9 3.5 0 4.2 2.3 4.2 5.3v7Z" /></svg>; }
function YoutubeIcon(props: React.SVGProps<SVGSVGElement>) { return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><path d="M21.6 7.2a3 3 0 0 0-2.1-2.1C17.6 4.6 12 4.6 12 4.6s-5.6 0-7.5.5a3 3 0 0 0-2.1 2.1C2 9.1 2 12 2 12s0 2.9.4 4.8a3 3 0 0 0 2.1 2.1c1.9.5 7.5.5 7.5.5s5.6 0 7.5-.5a3 3 0 0 0 2.1-2.1c.4-1.9.4-4.8.4-4.8s0-2.9-.4-4.8ZM10 15.4V8.6l5.8 3.4L10 15.4Z" /></svg>; }

function getFooterContext(pathname: string) {
  if (pathname.includes('physical-security') || pathname.includes('cctv-security')) return { label: 'Get a CCTV quote', intent: 'cctv_quote' };
  if (pathname.includes('network')) return { label: 'Plan your network', intent: 'networking_consultation' };
  if (pathname.includes('customised-setups')) return { label: 'Talk through your setup', intent: 'custom_setup_consultation' };
  if (pathname.includes('products')) return { label: 'Ask about a product', intent: 'product_enquiry' };
  return { label: 'Get help', intent: 'help_me_choose' };
}

export function Footer() {
  const pathname = usePathname();
  const { trackEvent } = useAnalytics();
  const [companyInfo, setCompanyInfo] = React.useState(DEFAULT_COMPANY_INFO);
  const [socialLinks, setSocialLinks] = React.useState<Record<string, string>>(FALLBACK_SOCIAL_LINKS);
  const context = getFooterContext(pathname || '');
  const supportEmail = companyInfo.supportEmail || DEFAULT_COMPANY_INFO.supportEmail;
  const supportPhone = companyInfo.supportPhone || DEFAULT_COMPANY_INFO.supportPhone;
  const address = companyInfo.registeredAddress || DEFAULT_COMPANY_INFO.registeredAddress;
  const contactHref = (intent: string) => `/contact?intent=${intent}&source=footer`;

  React.useEffect(() => {
    fetch('/company-info.json').then((response) => response.ok ? response.json() : null).then((data) => { if (data) setCompanyInfo((current) => ({ ...current, ...data })); }).catch(() => undefined);
    fetch('/api/settings?keys=facebookUrl,twitterUrl,instagramUrl,linkedinUrl,youtubeUrl,websiteUrl,phone,support_email').then((response) => response.ok ? response.json() : Promise.reject(new Error(String(response.status)))).then((data) => {
      const links = Object.fromEntries(Object.entries(data).filter(([key, value]) => Boolean(value) && !['phone', 'support_email'].includes(key))) as Record<string, string>;
      setSocialLinks((current) => ({ ...current, ...links }));
      if (data.phone || data.support_email) setCompanyInfo((current) => ({ ...current, supportPhone: data.phone || current.supportPhone, supportEmail: data.support_email || current.supportEmail }));
    }).catch((error) => logger.warn('footer_settings_load_failed', { error: error instanceof Error ? error.message : String(error) }));
  }, []);

  const socialPlatforms = [{ key: 'facebookUrl', icon: FacebookIcon, label: 'Facebook' }, { key: 'instagramUrl', icon: InstagramIcon, label: 'Instagram' }, { key: 'twitterUrl', icon: XIcon, label: 'X' }, { key: 'linkedinUrl', icon: LinkedinIcon, label: 'LinkedIn' }, { key: 'youtubeUrl', icon: YoutubeIcon, label: 'YouTube' }, { key: 'websiteUrl', icon: Globe, label: 'Website' }].filter(({ key }) => Boolean(socialLinks[key]));
  const trackFooterClick = (action: string, intent?: string) => trackEvent('footer_cta_click', { action, intent, page: pathname || '/' });
  const whatsappHref = `https://wa.me/919604136010?text=${encodeURIComponent('Hello TecBunny, I need help with a technology requirement.')}`;

  return <footer className="relative overflow-hidden border-t border-slate-800 bg-[#08152a] font-sans text-slate-300"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-400/60 to-transparent" /><div className="mx-auto max-w-screen-2xl px-5 py-10 sm:px-8 sm:py-14">
    <section className="rounded-2xl border border-cyan-300/20 bg-gradient-to-br from-blue-600/25 via-[#10244a] to-cyan-500/10 px-6 py-7 shadow-2xl shadow-blue-950/20 sm:px-9 sm:py-9" aria-labelledby="footer-help-heading"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">Talk to TecBunny</p><h2 id="footer-help-heading" className="text-2xl font-bold tracking-tight text-white sm:text-3xl">Not sure what you need?</h2><p className="mt-2 text-base leading-7 text-slate-300">Tell us about your requirement and we’ll help you choose the right technology solution.</p></div><div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap lg:justify-end"><Link href={contactHref(context.intent)} onClick={() => trackFooterClick('contextual_help', context.intent)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">{context.label}<ArrowRight className="h-4 w-4" /></Link><Link href={contactHref('quote_request')} onClick={() => trackFooterClick('quote_request', 'quote_request')} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-500/80 px-5 py-3 text-sm font-semibold text-white transition hover:border-cyan-300 hover:bg-white/10">Request a quote</Link><Link href={contactHref('engineer_consultation')} onClick={() => trackFooterClick('engineer_consultation', 'engineer_consultation')} className="inline-flex min-h-11 items-center justify-center gap-2 px-3 py-3 text-sm font-semibold text-cyan-200 transition hover:text-white">Talk to an engineer<ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <div className="mt-12 grid gap-10 lg:grid-cols-[1.35fr_3fr]"><section className="max-w-sm"><Link href="/" aria-label="TecBunny home" className="inline-flex"><Logo /></Link><p className="mt-5 text-base leading-7 text-slate-300">Technology, security and IT support for businesses and homes across Goa.</p><Link href={contactHref('help_me_choose')} onClick={() => trackFooterClick('brand_help', 'help_me_choose')} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg border border-cyan-300/50 px-4 py-2 text-sm font-semibold text-cyan-100 transition hover:bg-cyan-300 hover:text-slate-950">Get help choosing <ArrowRight className="h-4 w-4" /></Link></section><div className="hidden grid-cols-2 gap-x-8 gap-y-10 sm:grid lg:grid-cols-5">{linkGroups.map((group) => <nav key={group.title} aria-label={group.title}><h3 className="text-sm font-bold text-white">{group.title}</h3><ul className="mt-4 space-y-3">{group.links.map((link) => <li key={link.label}><Link href={link.href} className="text-sm leading-5 text-slate-300 transition hover:text-cyan-200">{link.label}</Link></li>)}</ul></nav>)}</div><div className="sm:hidden">{linkGroups.map((group) => <details key={group.title} className="border-b border-slate-700/80 py-3"><summary className="flex min-h-8 cursor-pointer list-none items-center justify-between text-sm font-bold text-white">{group.title}<ChevronDown className="h-4 w-4 text-cyan-300" /></summary><ul className="space-y-3 pb-2 pt-4">{group.links.map((link) => <li key={link.label}><Link href={link.href} className="block py-1 text-sm text-slate-300">{link.label}</Link></li>)}</ul></details>)}</div></div>
    <section className="mt-12 grid gap-7 border-y border-slate-700/80 py-8 md:grid-cols-[1fr_auto] md:items-center" aria-label="Contact TecBunny"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div className="flex gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-cyan-300" /><div><p className="text-sm font-bold text-white">Based in Goa</p><address className="mt-1 text-sm leading-6 not-italic">{address}</address></div></div><div className="space-y-2"><a href={`tel:${supportPhone.replace(/\s+/g, '')}`} onClick={() => trackFooterClick('call')} className="flex items-center gap-2 text-sm font-semibold text-white hover:text-cyan-200"><Phone className="h-4 w-4 text-cyan-300" />{supportPhone}</a><a href={`mailto:${supportEmail}`} onClick={() => trackFooterClick('email')} className="flex items-center gap-2 text-sm font-semibold text-white hover:text-cyan-200"><Mail className="h-4 w-4 text-cyan-300" />{supportEmail}</a></div><a href={whatsappHref} target="_blank" rel="noopener noreferrer" onClick={() => trackFooterClick('whatsapp')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-bold text-white transition hover:bg-emerald-400"><MessageCircle className="h-4 w-4" />WhatsApp us</a></div><a href="https://maps.google.com/?q=H.+No.+11,+Nhayginwada,+Parse,+Parxem,+Pernem,+North+Goa,+Goa+403512" target="_blank" rel="noopener noreferrer" onClick={() => trackFooterClick('directions')} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-600 px-4 py-2 text-sm font-semibold text-white transition hover:border-cyan-300 hover:text-cyan-100">Get directions</a></section>
    <div className="flex flex-col gap-6 py-7 text-sm md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap items-center gap-x-5 gap-y-2"><span>© 2026 TecBunny Solutions Pvt. Ltd.</span><span>CIN: {ENTITY.cin}</span><span>GSTIN: {companyInfo.gstin || DEFAULT_COMPANY_INFO.gstin}</span></div><nav aria-label="Legal" className="flex flex-wrap gap-x-5 gap-y-2"><Link href="/info/policies/privacy" className="hover:text-cyan-200">Privacy</Link><Link href="/info/policies/terms" className="hover:text-cyan-200">Terms</Link><Link href="/info/policies/terms" className="hover:text-cyan-200">Service terms</Link><Link href="/sitemap.xml" className="hover:text-cyan-200">Sitemap</Link></nav></div>
    {socialPlatforms.length > 0 && <div className="flex items-center gap-3 border-t border-slate-800 pt-6"><span className="mr-1 text-sm text-slate-400">Follow TecBunny</span>{socialPlatforms.map(({ key, icon: Icon, label }) => <a key={key} href={socialLinks[key]} target="_blank" rel="noopener noreferrer" aria-label={label} onClick={() => trackEvent('social_click', { platform: label })} className="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-slate-800 text-slate-300 transition hover:bg-cyan-300 hover:text-slate-950"><Icon className="h-4 w-4" /></a>)}</div>}
  </div></footer>;
}
