'use client';

import * as React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useAuth } from '@/lib/hooks';
import { createClient } from '@/lib/supabase/client';
import { Award, DollarSign, TrendingUp, Calendar } from 'lucide-react';
import type { Order } from '@/lib/types';

export default function SalesStaffReportsPage() {
  const { user } = useAuth();
  const supabase = React.useMemo(() => createClient(), []);
  const [invoices, setInvoices] = React.useState<Order[]>([]);
  const [stats, setStats] = React.useState({ count: 0, volume: 0 });
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    if (!user) return;

    const loadSelfReports = async () => {
      setLoading(true);
      try {
        const { data: orders, error } = await supabase
          .from('orders')
          .select('*')
          .eq('processed_by', user.id)
          .eq('status', 'Completed')
          .order('created_at', { ascending: false });

        if (error) throw error;

        const vol = (orders || []).reduce((acc, o) => acc + Number(o.total || 0), 0);
        setStats({
          count: orders?.length || 0,
          volume: vol,
        });
        setInvoices((orders as Order[]) || []);
      } catch (err) {
        console.error('Failed to load self reports:', err);
      } finally {
        setLoading(false);
      }
    };

    loadSelfReports();
  }, [user, supabase]);

  return (
    <div className="space-y-8 bg-background min-h-screen text-foreground p-1">
      <div>
        <p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Agent Console</p>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">My Performance Reports</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Tracking your individual volumes and processed invoices.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card className="bg-card border-border">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">My Sales Volume</CardTitle>
            <DollarSign className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            {loading ? (
              <Skeleton className="h-7 w-28 bg-muted" />
            ) : (
              <>
                <div className="text-2xl font-bold font-tech">₹{stats.volume.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</div>
                <p className="text-xs text-muted-foreground">Cumulative processed billing</p>
              </>
            )}
          </CardContent>
        </Card>

        <Card className="bg-card border-border">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Completed Orders</CardTitle>
            <TrendingUp className="h-4 w-4 text-emerald-500" />
          </CardHeader>
          <CardContent>
            {loading ? (
              <Skeleton className="h-7 w-16 bg-muted" />
            ) : (
              <>
                <div className="text-2xl font-bold font-tech">{stats.count}</div>
                <p className="text-xs text-muted-foreground">Invoices generated by you</p>
              </>
            )}
          </CardContent>
        </Card>

        <Card className="bg-card border-border">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Average Order Value</CardTitle>
            <Award className="h-4 w-4 text-amber-500" />
          </CardHeader>
          <CardContent>
            {loading ? (
              <Skeleton className="h-7 w-28 bg-muted" />
            ) : (
              <>
                <div className="text-2xl font-bold font-tech">
                  ₹{stats.count > 0 ? (stats.volume / stats.count).toLocaleString('en-IN', { maximumFractionDigits: 2 }) : '0'}
                </div>
                <p className="text-xs text-muted-foreground">AOV for completed sales</p>
              </>
            )}
          </CardContent>
        </Card>
      </div>

      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-primary" />
            My Invoiced Transactions
          </CardTitle>
          <CardDescription className="text-muted-foreground">
            A comprehensive list of completed sales invoices associated with your agent account.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader className="border-border">
              <TableRow className="border-border hover:bg-transparent">
                <TableHead className="text-muted-foreground">Invoice ID</TableHead>
                <TableHead className="text-muted-foreground">Customer</TableHead>
                <TableHead className="text-muted-foreground">Date</TableHead>
                <TableHead className="text-muted-foreground">Status</TableHead>
                <TableHead className="text-muted-foreground text-right">Total Amount</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                Array.from({ length: 3 }).map((_, i) => (
                  <TableRow key={i} className="border-border">
                    <TableCell><Skeleton className="h-5 w-24 bg-muted" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-32 bg-muted" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-20 bg-muted" /></TableCell>
                    <TableCell><Skeleton className="h-6 w-24 bg-muted" /></TableCell>
                    <TableCell className="text-right"><Skeleton className="h-5 w-20 ml-auto bg-muted" /></TableCell>
                  </TableRow>
                ))
              ) : invoices.length > 0 ? (
                invoices.map((invoice) => (
                  <TableRow key={invoice.id} className="border-border hover:bg-muted/30">
                    <TableCell className="font-mono text-xs text-muted-foreground">
                      {invoice.id.substring(0, 8)}...
                    </TableCell>
                    <TableCell className="font-semibold text-foreground">
                      {invoice.customer_name || 'Walk-in Customer'}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {new Date(invoice.created_at).toLocaleDateString()}
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="bg-emerald-500/10 text-emerald-500 border border-emerald-500/30">
                        {invoice.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right text-emerald-500 font-tech">
                      ₹{Number(invoice.total || 0).toFixed(2)}
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-muted-foreground py-6">
                    You have not processed any completed invoices yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
