import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, CheckCircle2, Phone } from 'lucide-react';

const categories = {
  'computers-mobiles': { title: 'Computers & Mobiles', intro: 'Get the right device, accessories, repair or upgrade without the guesswork.', items: ['Laptop & desktop sales', 'Computer accessories', 'Mobile phones & accessories', 'Computer & laptop repair', 'Mobile repair', 'Parts & upgrades'] },
  'networking-internet': { title: 'Networking & Internet', intro: 'Reliable internet and Wi-Fi for homes, shops and businesses.', items: ['Wi-Fi setup & repair', 'Router, repeater & range extender', 'Network configuration', 'Networking installation', 'Jio AirFiber new connection', 'Jio AirFiber repair'] },
  'cctv-security': { title: 'CCTV & Security', intro: 'Protect your home, shop or workplace with a setup that fits your space.', items: ['CCTV cameras', 'IP & Wi-Fi cameras', 'DVR & NVR systems', 'CCTV installation', 'CCTV repair', 'Security solutions'] },
  'government-business': { title: 'Government & Business Services', intro: 'Practical help with applications, documents and registrations.', items: ['PAN card', 'Residence, caste & divergence certificates', 'Application drafting & resume making', 'MSME & FSSAI', 'Shop & Establishment', 'GST registration'] },
  'financial-travel': { title: 'Financial & Travel Services', intro: 'Complete routine payments, insurance and travel bookings in one place.', items: ['Insurance & LIC payments', 'Domestic money transfer & AePS', 'Tax & fine payments', 'Flight tickets', 'Bus tickets', 'Train tickets'] },
} as const;

export function generateStaticParams() { return Object.keys(categories).map((category) => ({ category })); }
export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) {
  const { category } = await params; const data = categories[category as keyof typeof categories]; if (!data) notFound();
  const contactHref = `/contact?subject=sales&service=${category}&intent=service_request&source=service_category`;
  return <div className="bg-zinc-950 text-white"><section className="border-b border-zinc-800 bg-[radial-gradient(circle_at_80%_0%,rgba(37,99,235,.22),transparent_36%)]"><div className="tb-container py-14 sm:py-20"><Link href="/services" className="text-sm font-semibold text-blue-300 hover:text-white">← All services</Link><h1 className="mt-5 text-4xl font-bold sm:text-5xl">{data.title}</h1><p className="mt-5 max-w-2xl text-lg text-zinc-300">{data.intro}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={contactHref} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 font-bold hover:bg-blue-500">Request service <ArrowRight size={17}/></Link><a href="tel:+919604136010" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-zinc-700 px-5 font-bold hover:border-blue-400"><Phone size={17}/> Call TecBunny</a></div></div></section><section className="tb-container py-12 sm:py-16"><h2 className="text-2xl font-bold">What we can help with</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.items.map((item) => <div key={item} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><CheckCircle2 className="mb-4 text-blue-400" size={22}/><h3 className="text-lg font-bold">{item}</h3><p className="mt-2 text-sm text-zinc-400">Tell us what you need. We’ll confirm the next step, availability and pricing.</p><Link href={`${contactHref}&message=${encodeURIComponent(`I need help with ${item}.`)}`} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-blue-300">Get help <ArrowRight size={15}/></Link></div>)}</div></section><section className="border-t border-zinc-800 bg-zinc-900/40"><div className="tb-container py-12"><h2 className="text-2xl font-bold">How it works</h2><ol className="mt-6 grid gap-4 sm:grid-cols-3">{['Tell us what you need', 'We confirm the right service', 'Get help, a quote or booking'].map((step,index) => <li key={step} className="rounded-xl border border-zinc-800 bg-zinc-950 p-5"><span className="text-sm font-bold text-blue-400">0{index + 1}</span><p className="mt-2 font-semibold">{step}</p></li>)}</ol></div></section></div>;
}
